package primero;
// Generated 18-oct-2016 12:16:23 by Hibernate Tools 3.4.0.CR1

/**
 * Depart generated by hbm2java
 */
public class Depart implements java.io.Serializable {

	private DepartId id;

	public Depart() {
	}

	public Depart(DepartId id) {
		this.id = id;
	}

	public DepartId getId() {
		return this.id;
	}

	public void setId(DepartId id) {
		this.id = id;
	}

}
