package primero;
// Generated 18-oct-2016 12:16:23 by Hibernate Tools 3.4.0.CR1

/**
 * Emple generated by hbm2java
 */
public class Emple implements java.io.Serializable {

	private EmpleId id;

	public Emple() {
	}

	public Emple(EmpleId id) {
		this.id = id;
	}

	public EmpleId getId() {
		return this.id;
	}

	public void setId(EmpleId id) {
		this.id = id;
	}

}
