package primero;
// Generated 18-oct-2016 12:16:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmpleId generated by hbm2java
 */
public class EmpleId implements java.io.Serializable {

	private short empNo;
	private String apellido;
	private String oficio;
	private Short dir;
	private Date fechaAlt;
	private Integer salario;
	private Integer comision;
	private byte deptNo;

	public EmpleId() {
	}

	public EmpleId(short empNo, byte deptNo) {
		this.empNo = empNo;
		this.deptNo = deptNo;
	}

	public EmpleId(short empNo, String apellido, String oficio, Short dir, Date fechaAlt, Integer salario,
			Integer comision, byte deptNo) {
		this.empNo = empNo;
		this.apellido = apellido;
		this.oficio = oficio;
		this.dir = dir;
		this.fechaAlt = fechaAlt;
		this.salario = salario;
		this.comision = comision;
		this.deptNo = deptNo;
	}

	public short getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(short empNo) {
		this.empNo = empNo;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public Short getDir() {
		return this.dir;
	}

	public void setDir(Short dir) {
		this.dir = dir;
	}

	public Date getFechaAlt() {
		return this.fechaAlt;
	}

	public void setFechaAlt(Date fechaAlt) {
		this.fechaAlt = fechaAlt;
	}

	public Integer getSalario() {
		return this.salario;
	}

	public void setSalario(Integer salario) {
		this.salario = salario;
	}

	public Integer getComision() {
		return this.comision;
	}

	public void setComision(Integer comision) {
		this.comision = comision;
	}

	public byte getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(byte deptNo) {
		this.deptNo = deptNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmpleId))
			return false;
		EmpleId castOther = (EmpleId) other;

		return (this.getEmpNo() == castOther.getEmpNo())
				&& ((this.getApellido() == castOther.getApellido()) || (this.getApellido() != null
						&& castOther.getApellido() != null && this.getApellido().equals(castOther.getApellido())))
				&& ((this.getOficio() == castOther.getOficio()) || (this.getOficio() != null
						&& castOther.getOficio() != null && this.getOficio().equals(castOther.getOficio())))
				&& ((this.getDir() == castOther.getDir()) || (this.getDir() != null && castOther.getDir() != null
						&& this.getDir().equals(castOther.getDir())))
				&& ((this.getFechaAlt() == castOther.getFechaAlt()) || (this.getFechaAlt() != null
						&& castOther.getFechaAlt() != null && this.getFechaAlt().equals(castOther.getFechaAlt())))
				&& ((this.getSalario() == castOther.getSalario()) || (this.getSalario() != null
						&& castOther.getSalario() != null && this.getSalario().equals(castOther.getSalario())))
				&& ((this.getComision() == castOther.getComision()) || (this.getComision() != null
						&& castOther.getComision() != null && this.getComision().equals(castOther.getComision())))
				&& (this.getDeptNo() == castOther.getDeptNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmpNo();
		result = 37 * result + (getApellido() == null ? 0 : this.getApellido().hashCode());
		result = 37 * result + (getOficio() == null ? 0 : this.getOficio().hashCode());
		result = 37 * result + (getDir() == null ? 0 : this.getDir().hashCode());
		result = 37 * result + (getFechaAlt() == null ? 0 : this.getFechaAlt().hashCode());
		result = 37 * result + (getSalario() == null ? 0 : this.getSalario().hashCode());
		result = 37 * result + (getComision() == null ? 0 : this.getComision().hashCode());
		result = 37 * result + this.getDeptNo();
		return result;
	}

}
